const FETCH_MOVIES_START = 'FETCH_MOVIES_START';
const FETCH_MOVIE_START = 'FETCH_MOVIE_START';
const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
const FETCH_MOVIE_SUCCESS = 'FETCH_MOVIE_SUCCESS';
const FETCH_MOVIES_FAILURE = 'FETCH_MOVIES_FAILURE';
const FETCH_MOVIE_FAILURE = 'FETCH_MOVIE_FAILURE';
const QUERY_UPDATE = 'QUERY_UPDATE';
// FETCH_GENRES = 'FETCH_GENRES',
// RECEIVE_MOVIES = 'RECEIVE_MOVIES',
// RECEIVE_GENRES = 'RECEIVE_GENRES',
// QUERY_UPDATE = 'QUERY_UPDATE';

export {
  FETCH_MOVIES_START,
  FETCH_MOVIES_FAILURE,
  FETCH_MOVIES_SUCCESS,
  FETCH_MOVIE_SUCCESS,
  FETCH_MOVIE_FAILURE,
  FETCH_MOVIE_START,
  QUERY_UPDATE,
  // FETCH_GENRES,
  // RECEIVE_MOVIES,
  // RECEIVE_GENRES,
  // QUERY_UPDATE,
};
