const FETCH_MOVIES_REQUEST = 'FETCH_MOVIES_REQUEST',
  FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS',
  FETCH_MOVIES_ERROR = 'FETCH_MOVIES_ERROR',
  FETCH_GENRES_ERROR = 'FETCH_GENRES_ERROR',
  RECEIVE_MOVIES = 'RECEIVE_MOVIES',
  RECEIVE_GENRES = 'RECEIVE_GENRES';

export {
  FETCH_MOVIES_REQUEST,
  FETCH_MOVIES_SUCCESS,
  FETCH_MOVIES_ERROR,
  FETCH_GENRES_ERROR,
  RECEIVE_MOVIES,
  RECEIVE_GENRES,
};
